"""empty message

Revision ID: 018e6e12f57a
Revises: 8c41e009213d
Create Date: 2026-02-03 17:22:59.333904

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '018e6e12f57a'
down_revision = '8c41e009213d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
