"""empty message

Revision ID: 5764d2e37cd2
Revises: f4fc57dbd702
Create Date: 2026-02-03 17:30:30.012781

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '5764d2e37cd2'
down_revision = 'f4fc57dbd702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charityproject',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_amount', sa.Integer(), nullable=False),
    sa.Column('invested_amount', sa.Integer(), nullable=False),
    sa.Column('fully_invested', sa.Boolean(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('donation', sa.Column('full_amount', sa.Integer(), nullable=False))
    op.add_column('donation', sa.Column('invested_amount', sa.Integer(), nullable=False))
    op.add_column('donation', sa.Column('fully_invested', sa.Boolean(), nullable=False))
    op.add_column('donation', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('donation', sa.Column('close_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation', 'close_date')
    op.drop_column('donation', 'create_date')
    op.drop_column('donation', 'fully_invested')
    op.drop_column('donation', 'invested_amount')
    op.drop_column('donation', 'full_amount')
    op.drop_table('charityproject')
    # ### end Alembic commands ###
