"""empty message

Revision ID: 8c41e009213d
Revises: 
Create Date: 2026-02-03 17:21:22.395533

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '8c41e009213d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donation')
    # ### end Alembic commands ###
