"""empty message

Revision ID: f4fc57dbd702
Revises: 018e6e12f57a
Create Date: 2026-02-03 17:23:54.000555

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f4fc57dbd702'
down_revision = '018e6e12f57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
